platform :ios, '8.0' 

target ‘ButterflyDoctorVoice’ do
  pod 'AFNetworking', '~> 3.0'
  pod 'MJRefresh', '~> 3.1.10’
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'TYPagerController', '~> 1.0.2'
  pod 'Masonry', '~> 1.0.2'
  pod 'IQKeyboardManager', '~> 4.0.8'
  pod 'SDWebImage', '~> 3.8.0'
  pod 'TZImagePickerController'
  pod 'JPush'
  pod 'UMengUShare', '~> 6.4.2'
  pod 'OpenUDID', '~> 1.0.0'
end
